### ISSUE TITLE
Compatibility with NumBeam = 128

### ISSUE THREAD

**Issue by scaramouche88** [fzao/sonaris#1]
Hi,
first of all nice repo: much faster than other ones that I'm using.

When testing on video from our ARIS camera (numbeams = 128) I get the following error:
`  File "sonaris.py", line 657, in convert
    self.angular_converter()`
`File "sonaris.py", line 635, in angular_converter
    beamnum = self.lens_distorsion(self.nout, theta)` 
`File "sonaris.py", line 555, in lens_distorsion
    return np.round(factor * (a[0] * theta**3 +`
`UnboundLocalError: local variable 'factor' referenced before assignment
`

Looking at the code I think the error might come from the function lens_distorsion(self, nbeams, theta): 
https://github.com/fzao/sonaris/blob/dc24567919a0f7beee609e8bd2cc01d2414fc1e2/sonaris/sonaris.py#L542-L556
since the transformation is not defined for numbeams = 128

Any clues as to where you can find the right transformation for my case?
Thanks a lot!

**EDIT**
ok that function comes clearly from the ARISreader repo in matlab, no?
https://github.com/nilsolav/ARISreader/blob/973e391583ea4f2baa31be09ef57ed3cd69e9a84/lens_distortion.m#L1-L18 

Do you have any guess how to calculate such costants for my numbeans? Or the error is somewhere else?

**Comment by fzao** [comment]
Hello,

thanks for mentioning this issue. Yes, as indicated in the header of the file the conversion algorithm comes the ArisReader repo in Matlab. For the lens distortion part, the author mentioned that the values were set empiracally and I have no idea of what they could be for a number of beams equals to 128 ?

There are two values of parameters to set. For parameter 'a' it seems that there is only two possibilities. For parameter 'f' it's more tricky (between 1 and 4).

Would it be interesting/meaningful  to try to calibrate these two parameters by doing some tests of conversions ?

Regards

**Comment by scaramouche88** [comment]
Thank you for the quick reply.

Looking deeper in the code I see that I was wrong. At least not completely right.  
`lens_distorsion(self, nbeams, theta)` is called inside `angular_converter(self)`.
In this function the numbeam is read from the header
https://github.com/fzao/sonaris/blob/dc24567919a0f7beee609e8bd2cc01d2414fc1e2/sonaris/sonaris.py#L606
but then there is an operation that I don't get:
https://github.com/fzao/sonaris/blob/dc24567919a0f7beee609e8bd2cc01d2414fc1e2/sonaris/sonaris.py#L609
and this `nout` variable is given to the transformation:
https://github.com/fzao/sonaris/blob/dc24567919a0f7beee609e8bd2cc01d2414fc1e2/sonaris/sonaris.py#L635
So for numbeam = 128, nout is 509?

I think there is something I am missing. 
Usual number of beam are 12, 24, 48, 64, 96 and 128 if I remember right. 
So `nout` should be 45, 93, 189, 253, 381, 509. Only two of these numbers are present.

Anyhow, I will try a manual calibration. If I find it I will post it here.

For information: I work with an ARIS 3000 with 128 beams. With on many beams was your test video recorded?

**Comment by scaramouche88** [comment]
It is not perfect, but for now it works nicely adding these lines:
`elif nbeams == 509:`
`       factor = 5.45`
`       a = [.0030, -0.0055, 2.6829, 48.04]`

**Comment by fzao** [comment]
Thanks for this improvement. Would it be interesting or valuable to update Sonaris with this option if you agree ?

**Comment by fzao** [comment]
The update is pushed on github. Thank you!
